//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.CollectGoods = new HashSet<CollectGoods>();
            this.Comment = new HashSet<Comment>();
            this.Order_Goods = new HashSet<Order_Goods>();
            this.Picture = new HashSet<Picture>();
            this.ShopCart_Goods = new HashSet<ShopCart_Goods>();
        }
    
        public int goods_id { get; set; }
        public Nullable<int> goods_type_id { get; set; }
        public string goods_name { get; set; }
        public int goods_price { get; set; }
        public int goods_flag { get; set; }
        public string goods_info { get; set; }
        public int goods_count { get; set; }
        public System.DateTime goods_addTime { get; set; }
        public string goods_title { get; set; }
        public Nullable<int> sell_count { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectGoods> CollectGoods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual GoodsType GoodsType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Goods> Order_Goods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Picture> Picture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopCart_Goods> ShopCart_Goods { get; set; }
    }
}
