//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply
    {
        public int reply_id { get; set; }
        public string reply_content { get; set; }
        public System.DateTime reply_time { get; set; }
        public int reply_flag { get; set; }
        public int comment_id { get; set; }
        public int user_id { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
